"""empty message

Revision ID: a286230ed937
Revises: 
Create Date: 2017-08-04 01:55:33.981943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a286230ed937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('us_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'User', ['us_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('us_id')

    # ### end Alembic commands ###
